chore: disable sql connection when graphql is disabled
in-toto/archivista pull request #405
Opened 2024-10-23 01:03 UTC by mikhailswift

## What this PR does / why we need it

A user has expressed the desire to disable the SQL metadata store and graphql endpoints entirely, and just use Archivista to store and download attestations. This PR adds another config variable to support this, and disables both GraphQL and the SQL endpoint features if configured to do so.

## Which issue(s) this PR fixes (optional)

(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*

Fixes #

## Acceptance Criteria Met

- [ ] Docs changes if needed
- [ ] Testing changes if needed
- [ ] All workflow checks passing (automatically enforced)
- [ ] All review conversations resolved (automatically enforced)
- [ ] [DCO Sign-off](https://github.com/apps/dco)

**Special notes for your reviewer**:

2024-10-23 17:26 UTC, jkjell requested changes
Overall, this looks workable. I think the main addition would be an update to the README.md to describe the use case (and limitations) of leveraging Archivista as an attestation store only.

2024-10-25 07:51 UTC, kairoaraujo approved these changes

2024-10-25 09:52 UTC, kairoaraujo requested changes
There are some tests failing, I will also have a look.

2024-10-25 13:52 UTC, mikhailswift commented
Fixed the tests

2024-10-25 14:02 UTC, jkjell approved these changes

2024-10-25 18:30 UTC, kairoaraujo approved these changes

2024-10-25 18:30 UTC, merged